name: trigger
on: 
    push:
        branches: 
            master
jobs:
    job1:
        runs-on: ubuntu-22.04
        steps:
            - name: checkout code
              uses: actions/checkout@v5
            - name: set up python
              uses: actions/setup-python@v6 
              with:
                python-version: 3.13
            - name: Install dependencies
              run: |
                python -m venv venv
                source venv/bin/activate
                python -m install pip --upgrade pip
                pip install -r requirements.txt
            - name: Test
              run: |
                source venv/bin/activate
                python manage.py test
            - name: security-checks
              run: |
                source venv/bin/activate
                pip install pip-audit
                pip-audit
            - name: build
              run: python setup.py sdist bdist_wheel
