name: trigger
on: 
    push:
        branches: 
            master
    workflow_dispatch: 
jobs:
    job1:
        runs-on: ubuntu-22.04
        steps:
            - name: checkout code
              uses: actions/checkout@v5
            - name: set up python
              uses: actions/setup-python@v6 
              with:
                python-version: 3.13
            - name: Install dependencies
              run: |
                python -m venv venv
                source venv/bin/activate
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            - name: Test
              run: |
                source venv/bin/activate
                python manage.py test
            - name: reinstall pip
              run: |
                python -m ensurepip --upgrade
                python -m pip install pip==25.2.1
                pip --version
            - name: security-checks
              run: |
                source venv/bin/activate
                pip install pip-audit
                pip-audit -r requirements.txt
            - name: build
              run: |
                python manage.py collectstatic
